<?php
// Gegevens van muziek singles
$musicSingles = [
    [
        "title" => "Eminem - Godzilla ft. Juice WRLD",
        "artist" => "Eminem",
        "leeftijd" => "50",
        "genre" => "Rap",
        "image" => "/img/godzilla.jpg",
        "duur" => "2:15 Minuten",
        "datum" => "2019",
        "image1" => "/img/eminem1.jpg",
        "image2" => "/img/eminem2.jpg",
    ],
    [
        "title" => "XXXTENTACION - MOONLIGHT",
        "artist" => "XXXTENTACION",
        "leeftijd" => "20",
        "genre" => "Trap",
        "image" => "/img/moonlight.jpg",
        "duur" => "2:43 Minuten",
        "datum" => "2018",
        "image1" => "/img/xxx1.jpg",
        "image2" => "/img/xxx2.jpg",
    ],
    [
        "title" => "DaBaby - Rockstar feat. Roddy Ricch",
        "artist" => "DaBaby",
        "leeftijd" => "24",
        "genre" => "Trap",
        "image" => "/img/dababy.jpg",
        "duur" => "1:57 Minuten",
        "datum" => "2020",
        "image1" => "/img/dababy1.jpg",
        "image2" => "/img/dababy2.jpg",
    ],
    [
        "title" => "Roddy Ricch - Down Below",
        "artist" => "Roddy Ricch",
        "leeftijd" => "22",
        "genre" => "Rap",
        "image" => "/img/downbelow.jpg",
        "duur" => "3:43 Minuten",
        "datum" => "2021",
        "image1" => "/img/roddy1.jpg",
        "image2" => "/img/roddy2.jpg",
    ],
    [
        "title" => "YNW Melly - Murder On My Mind",
        "artist" => "YNW Melly",
        "leeftijd" => "21",
        "genre" => "Trap",
        "image" => "/img/Murder.jpg",
        "duur" => "2:10 Minuten",
        "datum" => "2019",
        "image1" => "/img/ynw1.jpg",
        "image2" => "/img/ynw2.jpg",
    ],
    [
        "title" => "Lil Tecca - Ransom",
        "artist" => "Lil Tecca",
        "leeftijd" => "19",
        "genre" => "Pop",
        "image" => "/img/Ransom.png",
        "duur" => "2:49 Minuten",
        "datum" => "2019",
        "image1" => "/img/tecca1.jpg",
        "image2" => "/img/tecca2.jpg",
    ],
    [
        "title" => "Future - Mask Off",
        "artist" => "Future",
        "leeftijd" => "30",
        "genre" => "Rap",
        "image" => "/img/future.jpg",
        "duur" => "3:23 Minuten",
        "datum" => "2017",
        "image1" => "/img/future1.jpg",
        "image2" => "/img/futere2.jpg",
    ],
    [
        "title" => "Lil Uzi Vert - XO Tour Llif3",
        "artist" => "Lil Uzi Vert",
        "leeftijd" => "24",
        "genre" => "Trap",
        "image" => "/img/vert.jpg",
        "duur" => "2:38 Minuten",
        "datum" => "2018",
        "image1" => "/img/vert1.jpg",
        "image2" => "/img/vert2.jpg",
    ],
    [
        "title" => "21 Savage - Bank Account",
        "artist" => "21 Savage",
        "leeftijd" => "27",
        "genre" => "Rap",
        "image" => "/img/21savage.jpg",
        "duur" => "2:47 Minuten",
        "datum" => "2017",
        "image1" => "/img/savage1.jpg",
        "image2" => "/img/savage2.jpg",
    ],
    [
        "title" => "Juice WRLD - Lucid Dreams",
        "artist" => "Juice WRLD",
        "leeftijd" => "21",
        "genre" => "Pop",
        "image" => "/img/juicewrld.jpg",
        "duur" => "3:50 Minuten",
        "datum" => "2018",
        "image1" => "/img/juice1.jpg",
        "image2" => "/img/juice2.jpg",
    ],
    // Voeg hier meer gegevens toe
];
